<?php

namespace Database\Seeders;

use App\Models\Store;
use Illuminate\Database\Seeder;

class StoreSeeder extends Seeder
{
    public function run(): void
    {
        $stores = [
            [
                'store_name'         => 'PrintPro Manhattan',
                'store_code'         => 'PP-MH-001',
                'owner_name'         => 'James Wilson',
                'email'              => 'manhattan@printpro.com',
                'phone'              => '(212) 555-0123',
                'address'            => '350 5th Avenue, Suite 200',
                'city'               => 'New York',
                'state'              => 'NY',
                'zip_code'           => '10118',
                'country'            => 'USA',
                'printer_ip_address' => '192.168.1.101',
                'printer_port'       => 9100,
                'printer_name'       => 'Epson TM-T82III',
                'printer_type'       => 'thermal',
                'paper_size'         => 'Receipt_80mm',
                'is_active'          => true,
                'opening_time'       => '08:00',
                'closing_time'       => '20:00',
                'gst_number'         => '13-1234567',
            ],
            [
                'store_name'         => 'PrintPro Brooklyn',
                'store_code'         => 'PP-BK-002',
                'owner_name'         => 'Sarah Johnson',
                'email'              => 'brooklyn@printpro.com',
                'phone'              => '(718) 555-0456',
                'address'            => '123 Atlantic Avenue',
                'city'               => 'Brooklyn',
                'state'              => 'NY',
                'zip_code'           => '11201',
                'country'            => 'USA',
                'printer_ip_address' => '192.168.1.102',
                'printer_port'       => 9100,
                'printer_name'       => 'HP LaserJet Pro M404dn',
                'printer_type'       => 'laser',
                'paper_size'         => 'Letter',
                'is_active'          => true,
                'opening_time'       => '09:00',
                'closing_time'       => '19:00',
                'gst_number'         => '11-2345678',
            ],
            [
                'store_name'         => 'PrintPro Los Angeles',
                'store_code'         => 'PP-LA-003',
                'owner_name'         => 'Michael Chen',
                'email'              => 'la@printpro.com',
                'phone'              => '(323) 555-0789',
                'address'            => '6801 Hollywood Blvd, Suite 100',
                'city'               => 'Los Angeles',
                'state'              => 'CA',
                'zip_code'           => '90028',
                'country'            => 'USA',
                'printer_ip_address' => '192.168.2.50',
                'printer_port'       => 9100,
                'printer_name'       => 'Canon PIXMA G3010',
                'printer_type'       => 'inkjet',
                'paper_size'         => 'Letter',
                'is_active'          => true,
                'opening_time'       => '09:00',
                'closing_time'       => '21:00',
                'gst_number'         => '95-3456789',
            ],
            [
                'store_name'         => 'Capital Print Hub',
                'store_code'         => 'CPH-DC-004',
                'owner_name'         => 'David Martinez',
                'email'              => 'dc@capitalprinthub.com',
                'phone'              => '(202) 555-0321',
                'address'            => '1600 K Street NW, Suite 300',
                'city'               => 'Washington',
                'state'              => 'DC',
                'zip_code'           => '20006',
                'country'            => 'USA',
                'printer_ip_address' => '10.0.0.55',
                'printer_port'       => 9100,
                'printer_name'       => 'Brother HL-L2321D',
                'printer_type'       => 'laser',
                'paper_size'         => 'Letter',
                'is_active'          => true,
                'opening_time'       => '08:30',
                'closing_time'       => '18:00',
                'gst_number'         => '52-4567890',
            ],
            [
                'store_name'         => 'Chicago PrintStation',
                'store_code'         => 'CPS-IL-005',
                'owner_name'         => 'Emily Thompson',
                'email'              => 'chicago@printstation.com',
                'phone'              => '(312) 555-0654',
                'address'            => '233 S Wacker Dr, Suite 400',
                'city'               => 'Chicago',
                'state'              => 'IL',
                'zip_code'           => '60606',
                'country'            => 'USA',
                'printer_ip_address' => '192.168.10.20',
                'printer_port'       => 9100,
                'printer_name'       => 'Epson L3250',
                'printer_type'       => 'inkjet',
                'paper_size'         => 'Letter',
                'is_active'          => true,
                'opening_time'       => '08:00',
                'closing_time'       => '20:00',
                'gst_number'         => '36-5678901',
            ],
            [
                'store_name'         => 'Miami Prints Express',
                'store_code'         => 'MPE-FL-006',
                'owner_name'         => 'Carlos Rodriguez',
                'email'              => 'miami@printsexpress.com',
                'phone'              => '(305) 555-0987',
                'address'            => '100 Biscayne Blvd, Suite 150',
                'city'               => 'Miami',
                'state'              => 'FL',
                'zip_code'           => '33132',
                'country'            => 'USA',
                'printer_ip_address' => '172.16.0.110',
                'printer_port'       => 9100,
                'printer_name'       => 'Star TSP143III',
                'printer_type'       => 'thermal',
                'paper_size'         => 'Receipt_58mm',
                'is_active'          => true,
                'opening_time'       => '09:00',
                'closing_time'       => '21:00',
                'gst_number'         => '65-6789012',
            ],
            [
                'store_name'         => 'Seattle Digital Print',
                'store_code'         => 'SDP-WA-007',
                'owner_name'         => 'Kevin O\'Brien',
                'email'              => 'seattle@digitalprint.com',
                'phone'              => '(206) 555-0246',
                'address'            => '401 Pine Street, Suite 500',
                'city'               => 'Seattle',
                'state'              => 'WA',
                'zip_code'           => '98101',
                'country'            => 'USA',
                'printer_ip_address' => '192.168.5.200',
                'printer_port'       => 9100,
                'printer_name'       => 'HP OfficeJet Pro 9015',
                'printer_type'       => 'inkjet',
                'paper_size'         => 'Letter',
                'is_active'          => false,
                'opening_time'       => '10:00',
                'closing_time'       => '18:00',
                'gst_number'         => '91-7890123',
                'notes'              => 'Temporarily closed for renovation',
            ],
            [
                'store_name'         => 'Boston Print Works',
                'store_code'         => 'BPW-MA-008',
                'owner_name'         => 'Lisa Anderson',
                'email'              => 'boston@printworks.com',
                'phone'              => '(617) 555-0135',
                'address'            => '1 Federal Street, Suite 200',
                'city'               => 'Boston',
                'state'              => 'MA',
                'zip_code'           => '02110',
                'country'            => 'USA',
                'printer_ip_address' => '10.10.10.25',
                'printer_port'       => 9100,
                'printer_name'       => 'Ricoh SP 210',
                'printer_type'       => 'laser',
                'paper_size'         => 'Letter',
                'is_active'          => true,
                'opening_time'       => '08:00',
                'closing_time'       => '19:00',
                'gst_number'         => '04-8901234',
            ],
        ];

        foreach ($stores as $store) {
            Store::updateOrCreate(
                ['store_code' => $store['store_code']],
                $store
            );
        }
    }
}
