<?php
require 'vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

// Re-insert old products with category_id = 7 (Greeting Cards parent)
$greetingCardsId = \App\Models\Category::where('name', 'Greeting Cards')->first()->id;
$magnetsId = \App\Models\Category::where('name', 'Magnets')->first()->id;

// Disable foreign key checks
\DB::statement('SET FOREIGN_KEY_CHECKS=0;');

// Insert products from backup - assign first 4 to Greeting Cards, rest to Magnets
\DB::table('products')->insert([
    ['id' => 1, 'category_id' => $greetingCardsId, 'name' => 'Classic Acrylic Wall Photo', 'slug' => 'classic-acrylic-wall-photo', 'short_description' => 'Transform your favorite photo into a stunning acrylic wall piece.', 'description' => 'Classic acrylic wall photo with vivid colors.', 'base_price' => 1299.00, 'compare_price' => 1999.00, 'sku' => 'ACP-001', 'frame_image' => 'products/frames/EGis0PMe5QJGSOULCEOE9mZp23amnKbcAHy3ErO0.png', 'sample_image' => 'products/samples/IMWkvZbIPCaSxvI7QmLmcRLiayIfKl7OkUZu5m44.jpg', 'min_images' => 1, 'max_images' => 1, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => '{"frame":{"left":0,"top":0,"scaleX":0.6,"scaleY":0.6004},"masks":[{"type":"square","left":148.53,"top":149.04,"scaleX":2.9001,"scaleY":2.9001,"angle":0,"width":100,"height":100,"fill":"#ff0000","stroke":"#7a7a7a","strokeWidth":2,"opacity":1}],"canvasWidth":600,"canvasHeight":583}', 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 1, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 3, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 2, 'category_id' => $greetingCardsId, 'name' => 'Acrylic Photo Collage Board', 'slug' => 'acrylic-photo-collage-board', 'short_description' => 'Create a stunning multi-photo collage on premium acrylic.', 'description' => 'Collage board with sleek modern look.', 'base_price' => 1999.00, 'compare_price' => 2999.00, 'sku' => 'APC-002', 'frame_image' => 'products/frames/p3Vgla5xwXLRHCe4Qsd43k2i3aRfIcoXuAHBsgDl.png', 'sample_image' => 'products/samples/Z1rENJJ5j4kKKGZwbESsRJ71pgX3W57UDAayAsdb.webp', 'min_images' => 2, 'max_images' => 9, 'allowed_print_types' => '["noritsu","standard"]', 'customization_config' => null, 'mask_data' => '{"frame":{"left":0,"top":0,"scaleX":0.5556,"scaleY":0.5556},"masks":[{"type":"square","left":135.53,"top":339.8,"scaleX":3.0392,"scaleY":1.9992,"angle":354.82,"width":100,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1},{"type":"square","left":119.95,"top":91.99,"scaleX":1.4814,"scaleY":1.7682,"angle":355.27,"width":100,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1},{"type":"square","left":275.27,"top":79.18,"scaleX":1.4915,"scaleY":1.7939,"angle":355.07,"width":100,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1}],"canvasWidth":600,"canvasHeight":600}', 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 1, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 2, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 3, 'category_id' => $greetingCardsId, 'name' => 'Gallery Canvas Print', 'slug' => 'gallery-canvas-print', 'short_description' => 'Museum-quality canvas print stretched on solid wood frame.', 'description' => 'Premium canvas prints with archival inks.', 'base_price' => 999.00, 'compare_price' => 1499.00, 'sku' => 'CNV-001', 'frame_image' => 'products/frames/1TI2d8IxC3PQG6JXJQ0jqxZNGjVxMT58RN1BLCKn.jpg', 'sample_image' => 'products/samples/udbyFqR0IabfoQQXmHwqlm99dYM2yLdFbJ7QCVFL.jpg', 'min_images' => 1, 'max_images' => 6, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => '{"frame":{"left":0,"top":0,"scaleX":0.9804,"scaleY":0.9809},"masks":[{"type":"square","left":231.97,"top":25.16,"scaleX":1.3182,"scaleY":1.9604,"angle":0,"width":100,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1},{"type":"square","left":421.01,"top":64.05,"scaleX":1.4642,"scaleY":1.4642,"angle":0,"width":100,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1},{"type":"oval","left":53.76,"top":16.46,"scaleX":1.052,"scaleY":1.052,"angle":0,"width":100,"height":140,"rx":50,"ry":70,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1}],"canvasWidth":600,"canvasHeight":257}', 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 1, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 6, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 4, 'category_id' => $greetingCardsId, 'name' => 'Split Canvas Set', 'slug' => 'split-canvas-set', 'short_description' => 'Your photo split across multiple canvas panels.', 'description' => 'Bold split canvas sets.', 'base_price' => 2499.00, 'compare_price' => 3499.00, 'sku' => 'CNV-002', 'frame_image' => 'products/frames/J3FThYRSHxca68qddpVcSGfdaByNNGElLEK2GHKV.png', 'sample_image' => 'products/samples/ugt2RbFjU872E8CgNJ8gewkY9Q0gleukAJcu4aiJ.png', 'min_images' => 1, 'max_images' => 1, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => '{"frame":{"left":0,"top":0,"scaleX":1,"scaleY":1},"masks":[{"type":"rectangle","left":31.02,"top":51.21,"scaleX":3.5063,"scaleY":3.4054,"angle":357.36,"width":150,"height":100,"fill":"rgba(0, 100, 255, 0.45)","stroke":"rgba(0, 80, 220, 0.9)","strokeWidth":2,"opacity":1}],"canvasWidth":600,"canvasHeight":422}', 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 1, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 0, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 5, 'category_id' => $magnetsId, 'name' => 'Premium Poster Print', 'slug' => 'premium-poster-print', 'short_description' => 'Affordable high-quality poster prints.', 'description' => 'Stunning poster prints.', 'base_price' => 399.00, 'compare_price' => 599.00, 'sku' => 'PST-001', 'frame_image' => null, 'sample_image' => null, 'min_images' => 1, 'max_images' => 1, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => null, 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 0, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 0, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 6, 'category_id' => $magnetsId, 'name' => 'Custom Framed Portrait', 'slug' => 'custom-framed-portrait', 'short_description' => 'Beautifully framed photo prints.', 'description' => 'Custom framing service.', 'base_price' => 1799.00, 'compare_price' => 2499.00, 'sku' => 'FRM-001', 'frame_image' => null, 'sample_image' => null, 'min_images' => 1, 'max_images' => 1, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => null, 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 0, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 0, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 7, 'category_id' => $magnetsId, 'name' => 'Heart-Shape Photo Collage', 'slug' => 'heart-shape-photo-collage', 'short_description' => 'Photos arranged in a heart shape.', 'description' => 'Heart-shaped photo collage.', 'base_price' => 1499.00, 'compare_price' => 2199.00, 'sku' => 'CLG-001', 'frame_image' => null, 'sample_image' => null, 'min_images' => 10, 'max_images' => 30, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => null, 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 1, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 0, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
    ['id' => 8, 'category_id' => $magnetsId, 'name' => 'Brushed Aluminum Photo', 'slug' => 'brushed-aluminum-photo', 'short_description' => 'Modern metal prints with brushed aluminum finish.', 'description' => 'Brushed aluminum prints.', 'base_price' => 2299.00, 'compare_price' => 3299.00, 'sku' => 'MTL-001', 'frame_image' => null, 'sample_image' => null, 'min_images' => 1, 'max_images' => 1, 'allowed_print_types' => '["noritsu"]', 'customization_config' => null, 'mask_data' => null, 'meta_title' => null, 'meta_description' => null, 'meta_keywords' => null, 'is_featured' => 0, 'is_active' => 1, 'sort_order' => 0, 'views_count' => 1, 'created_at' => now(), 'updated_at' => now(), 'deleted_at' => null],
]);

\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

echo "Done! Products restored.\n";
echo "Products count: " . \App\Models\Product::count() . "\n";
